package student
import indi.taicw.drools.entity.Student

/*
 当前规则文件用于测试Drools提供的内置方法
*/


rule "rule_student_age小于10岁"
    //salience 10
    when
        $s:Student(age < 10)
    then
//        $s.setAge(15);
//        update($s)
        retract($s)
        System.out.println("规则rule_student_age小于10岁触发");
end

rule "rule_student_age小于20岁同时大于10岁"
    when
        $s:Student(age < 20 && age > 10)
    then
//        $s.setAge(25);
//        update($s)
        System.out.println("规则rule_student_age小于20岁同时大于10岁触发");
end

rule "rule_student_age大于20岁"
    when
        $s:Student(age > 20)
    then
        System.out.println("规则rule_student_age大于20岁触发");
end

rule "rule_student_age等于5岁"
    when
        $s:Student(age == 5)
    then
        Student student = new Student();
        student.setAge(30);
        insert(student);
        System.out.println("规则rule_student_age等于5岁触发");
end

